### ISSUE TITLE
Req Register should redirect to homepage or login if successful

### ISSUE THREAD

**Issue by yzdnaufan** [capstoneB11/web-frontend#24]
Kadang bikin aneh aja abis register yang success kok gaada respon apa apa

**Comment by ranggarahman** [comment]
udah ya 🥺🥺🥺😤😤😤😤😤😤😤😤

**Comment by ranggarahman** [comment]
EH register ya.. salah baca mamaf

**Comment by ranggarahman** [comment]
UDAH ya lihat commi commit#30
